#!/usr/bin/env bash
#
# Generate the per-image linter tables in LINTERS.md from the Dockerfiles.
#
# There is one image variant per images/<variant>/Dockerfile, and one table region per variant in
# LINTERS.md, marked by <!-- linters:<variant>:start --> / <!-- linters:<variant>:end --> and filled
# from that variant's Dockerfile. The Dockerfiles are the single source of truth.
#
# For each Lane-1 tool the version and upstream image come from its `FROM <img>:<tag>@<digest> AS
# <name>` line; the descriptive bits (what it lints, its repo link) come from a `# linter:`
# annotation directly above that FROM:
#
#     # linter: lints: Dockerfiles | repo: https://github.com/hadolint/hadolint
#     FROM hadolint/hadolint:v2.14.0-alpine@sha256:... AS hadolint
#
# A Lane-2 tool (apt/npm/pip, or a downloaded binary; no FROM) carries its own name in the
# annotation, with the version either inline (`| version: x.y.z |`) or, for a downloaded binary, in
# the first `ARG <NAME>_VERSION=` line below it (so the ARG stays the single version source and
# Renovate can bump it):
#
#     # linter: tool: ktlint | lane: 2 | lints: Kotlin | repo: https://github.com/ktlint/ktlint
#     ARG KTLINT_VERSION=1.8.0
#
# The tables are written between the markers in LINTERS.md; the rest of that file is hand-written and
# left untouched. Each generated table is prefixed with an `<!-- Autogenerated ... -->` comment so a
# future editor looking at the raw source knows that region is regenerated and not to hand-edit it.
#
# Usage:
#   ./scripts/gen-linters.sh           rewrite every table in LINTERS.md
#   ./scripts/gen-linters.sh --check   exit non-zero if LINTERS.md is stale; write nothing
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

manifest='LINTERS.md'

tmp_table=''
tmp_out=''
cleanup() {
  if [ -n "${tmp_table:-}" ]; then rm -f "$tmp_table"; fi
  if [ -n "${tmp_out:-}" ]; then rm -f "$tmp_out" "${tmp_out}.new"; fi
}
trap cleanup EXIT

# Image variants: one per images/<variant>/Dockerfile.
list_variants() {
  for d in images/*/; do
    [ -f "${d}Dockerfile" ] && basename "$d"
  done
}

# Emit the markdown table (header + one row per tool) for the Dockerfile in $1, to stdout.
gen_table() {
  awk -v src="$1" '
    function trim(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); return s }
    function field(ann, key,   n, parts, i, kv, p, k) {
      n = split(ann, parts, "|")
      for (i = 1; i <= n; i++) {
        kv = parts[i]; p = index(kv, ":")
        if (p > 0) {
          k = trim(substr(kv, 1, p - 1))
          if (k == key) return trim(substr(kv, p + 1))
        }
      }
      return ""
    }
    function lane_label(l) {
      if (l == "1") return "1 (static)"
      if (l == "2") return "2"
      return l
    }
    function emit(name, ver, lane, lints, repo, img,   imgcell) {
      imgcell = (img == "") ? "n/a" : ("`" img "`")
      printf "| [%s](%s) | %s | %s | %s | %s |\n", name, repo, ver, lane_label(lane), lints, imgcell
    }
    BEGIN {
      print "<!-- Autogenerated by scripts/gen-linters.sh from " src ". Do not edit by hand. -->"
      print "| Tool | Version | Lane | Lints | Upstream image |"
      print "| --- | --- | --- | --- | --- |"
      pending = 0
      pending_arg = 0
    }
    /^[[:space:]]*#[[:space:]]*linter:/ {
      ann = $0
      sub(/^[[:space:]]*#[[:space:]]*linter:[[:space:]]*/, "", ann)
      if (field(ann, "tool") != "") {
        lane = field(ann, "lane"); if (lane == "") lane = "2"
        ver = field(ann, "version")
        if (ver != "") {
          emit(field(ann, "tool"), ver, lane, field(ann, "lints"), field(ann, "repo"), field(ann, "image"))
        } else {
          # No version in the annotation: it comes from the first `ARG <NAME>=<value>` line
          # below (a downloaded-binary Lane-2 tool keeps the version in one ARG, so it stays
          # the single source of truth and Renovate can bump it).
          a_tool = field(ann, "tool"); a_lane = lane
          a_lints = field(ann, "lints"); a_repo = field(ann, "repo"); a_img = field(ann, "image")
          pending_arg = 1
        }
        pending = 0
      } else {
        p_lints = field(ann, "lints"); p_repo = field(ann, "repo")
        pending = 1
      }
      next
    }
    pending_arg && /^[[:space:]]*ARG[[:space:]]+[A-Za-z_][A-Za-z0-9_]*=/ {
      ver = $0
      sub(/^[[:space:]]*ARG[[:space:]]+[A-Za-z_][A-Za-z0-9_]*=/, "", ver)
      ver = trim(ver); gsub(/^"|"$/, "", ver)
      emit(a_tool, ver, a_lane, a_lints, a_repo, a_img)
      pending_arg = 0
      next
    }
    pending && /^[[:space:]]*FROM[[:space:]]/ {
      ref = $2
      amp = index(ref, "@")
      imgtag = (amp > 0) ? substr(ref, 1, amp - 1) : ref
      lc = 0
      for (i = length(imgtag); i >= 1; i--) if (substr(imgtag, i, 1) == ":") { lc = i; break }
      tag = (lc > 0) ? substr(imgtag, lc + 1) : ""
      name = ""
      for (i = 3; i < NF; i++) if (toupper($i) == "AS") { name = $(i + 1); break }
      emit(name, tag, "1", p_lints, p_repo, imgtag)
      pending = 0
    }
  ' "$1"
}

# Print $1 with the region between markers $3 / $4 replaced by the contents of file $2.
replace_section() {
  awk -v tablefile="$2" -v s="$3" -v e="$4" '
    BEGIN { while ((getline line < tablefile) > 0) tbl = tbl line "\n"; sub(/\n$/, "", tbl) }
    index($0, s) { print; print tbl; skip = 1; next }
    index($0, e) { skip = 0; print; next }
    skip { next }
    { print }
  ' "$1"
}

main() {
  variant_list=()
  while IFS= read -r v; do
    if [ -n "$v" ]; then variant_list+=("$v"); fi
  done < <(list_variants)

  if [ "${#variant_list[@]}" -eq 0 ]; then
    echo "error: no image variants found (images/*/Dockerfile)" >&2
    exit 2
  fi

  tmp_table="$(mktemp)"
  tmp_out="$(mktemp)"
  cp "$manifest" "$tmp_out"

  for v in "${variant_list[@]}"; do
    start="<!-- linters:${v}:start -->"
    end="<!-- linters:${v}:end -->"
    if ! grep -qF "$start" "$tmp_out" || ! grep -qF "$end" "$tmp_out"; then
      printf 'error: %s is missing the "%s" / "%s" markers for variant %s\n' "$manifest" "$start" "$end" "$v" >&2
      exit 2
    fi
    gen_table "images/${v}/Dockerfile" >"$tmp_table"
    replace_section "$tmp_out" "$tmp_table" "$start" "$end" >"${tmp_out}.new"
    mv "${tmp_out}.new" "$tmp_out"
  done

  if [ "${1:-}" = '--check' ]; then
    if diff -u "$manifest" "$tmp_out" >/dev/null; then
      echo "LINTERS.md is up to date"
    else
      echo "LINTERS.md is stale; run ./scripts/gen-linters.sh" >&2
      diff -u "$manifest" "$tmp_out" >&2 || true
      exit 1
    fi
  else
    cat "$tmp_out" >"$manifest"
    echo "updated $manifest"
  fi
}

main "$@"
